### ISSUE TITLE
Discrepancy in hyperparameters defaults

### ISSUE THREAD

**Issue by ChristK** [volkerschmid/bamp#2]
Dear Volker

Many thanks for all your work on this very useful package.

Looking at the default values for the hyperparameters in the bamp() function, I notice that the Gamma distribution for age uses a=1 and b=0.5. Shouldn't be b=0.0005 as with the period and cohort default values? 

I notice that the documentation for the function states that the b for age is 0.0005. Could you please clarify? 

All the best
Chris

**Comment by ChristK** [comment]
Argh! I see now in the news that the change was intentional. So all it needs to get updated is the documentation as well.

**Comment by volkerschmid** [comment]
Dear Chris,
thanks for your comment. Indeed the change was intentional, I will change the documentation accordingly. 
In general, I am not happy about providing simple default settings for hyper priors. I will see if I can find a more appropriate way of handling this.
Best
Volker

**Comment by ChristK** [comment]
Thank you!
